#! /bin/bash

./les_typedata.py > jake_log.txt
if [ $? -gt 0 ]; then
    echo -e ""
    echo -e "###############"
    echo -e "ERROR "
    echo -e "###############"
    echo -e ""
		exit
fi

diff jake_log.txt jake_correctTestOutput.txt
if [ $? -gt 0 ]; then
    echo -e ""
    echo -e "############"
    echo -e "TESTS FAILED"
    echo -e "############"
    echo -e ""
		exit
else
    echo -e ""
    echo -e "############"
    echo -e "TESTS PASSED"
    echo -e "############"
    echo -e ""
		exit
fi
